/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alunoces
 */
public class T_Principal extends javax.swing.JFrame {
    
    public static String tipoUsuario;

    /**
     * Creates new form T_Principal
     */
    public T_Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.gray);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        barraMenu = new javax.swing.JMenuBar();
        mncadastrar = new javax.swing.JMenu();
        mnicliente = new javax.swing.JMenuItem();
        mniproduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnisair = new javax.swing.JMenuItem();
        mnpesquisa = new javax.swing.JMenu();
        mncliente = new javax.swing.JMenu();
        mnifisico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mncadastrar.setMnemonic('C');
        mncadastrar.setText("Cadastrar");
        mncadastrar.setToolTipText("");
        mncadastrar.setEnabled(false);

        mnicliente.setMnemonic('C');
        mnicliente.setText("Cliente");
        mnicliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniclienteActionPerformed(evt);
            }
        });
        mncadastrar.add(mnicliente);

        mniproduto.setMnemonic('P');
        mniproduto.setText("Produto");
        mniproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniprodutoActionPerformed(evt);
            }
        });
        mncadastrar.add(mniproduto);
        mncadastrar.add(jSeparator2);

        mnisair.setMnemonic('S');
        mnisair.setText("Sair");
        mnisair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisairActionPerformed(evt);
            }
        });
        mncadastrar.add(mnisair);

        barraMenu.add(mncadastrar);

        mnpesquisa.setMnemonic('P');
        mnpesquisa.setText("Pesquisar");
        mnpesquisa.setEnabled(false);

        mncliente.setText("Cliente");

        mnifisico.setText("Fisico");
        mncliente.add(mnifisico);

        mnpesquisa.add(mncliente);

        barraMenu.add(mnpesquisa);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniclienteActionPerformed
        new FrmCliente(null, true).setVisible(true);
    }//GEN-LAST:event_mniclienteActionPerformed

    private void mnisairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisairActionPerformed
        int status = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair da aplicação", "Fechar", 
                JOptionPane.YES_NO_OPTION);
        if(status == JOptionPane.YES_OPTION){
            System.exit(0);            
        }
    }//GEN-LAST:event_mnisairActionPerformed

    private void mniprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniprodutoActionPerformed
        new FrmProduto(null, true).setVisible(true);
    }//GEN-LAST:event_mniprodutoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        switch(tipoUsuario){
            case "A":
                mncadastrar.setEnabled(true);                
            break;
            case "B":                
                mnpesquisa.setEnabled(true);
            break;                
        }        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mncadastrar;
    private javax.swing.JMenu mncliente;
    private javax.swing.JMenuItem mnicliente;
    private javax.swing.JMenuItem mnifisico;
    private javax.swing.JMenuItem mniproduto;
    private javax.swing.JMenuItem mnisair;
    private javax.swing.JMenu mnpesquisa;
    // End of variables declaration//GEN-END:variables
}
